esphome:
  name: esp32-4848s040
  friendly_name: ESP32 Display 4.0

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  framework:
    type: esp-idf

psram:
  mode: octal
  speed: 80MHz


# Enable logging
logger:
  level: debug

# Enable Home Assistant API
api:
  encryption:
    key: "qPC7EIAr2+6hP7NN5HkG5JSh/p5e9oCa8MR/TyhMfz0="

ota:
  - platform: esphome
    password: "1f23fda514f4a4b958e65a6d6f9d0a60"
    on_begin: # prevent screen flickering during OTA
      - light.turn_off:
          id: display_backlight
          transition_length: 0s
      - lambda: "id(display_backlight).loop();"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

switch:
  - platform: gpio
    name: Relay 1
    pin:
      number: GPIO40
      inverted: true
  - platform: gpio
    name: Relay 2
    pin:
      number: GPIO2
      inverted: true
  - platform: gpio
    name: Relay 3
    pin:
      number: GPIO1
      inverted: true

output:
  - platform: ledc
    id: backlight_output
    pin: GPIO38
    frequency: 150Hz
    min_power: 0.01
    zero_means_zero: true

light:
  - platform: monochromatic
    name: Backlight
    id: display_backlight
    output: backlight_output
    restore_mode: ALWAYS_ON
    default_transition_length: 1s

spi:
  - id: lcd_spi
    clk_pin: GPIO48
    mosi_pin: GPIO47

font:
  - file: "fonts/DejaVuSans.ttf"
    id: font_normal
    size: 20
    bpp: 2
    glyphs: [
      0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZäöüÄÖÜß!,
      (,),+,-,_,.,°,•,:,;,?
      ]
  - file: "fonts/DejaVuSans-Bold.ttf"
    id: font_bold
    size: 20
    bpp: 2
    glyphs: [
      0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZäöüÄÖÜß!,
      (,),+,-,_,.,°,•,:,;,?
      ]

i2c:
  id: touchscreen_bus
  sda: GPIO19
  scl:
    number: 45
    ignore_strapping_warning: true

display:
  - platform: st7701s
    id: tft_display
    dimensions:
      width: 480
      height: 480
    #    rotation: 270    #uncomment for placement with down-facing USB socket
    spi_mode: MODE3
    data_rate: 2MHz
    color_order: RGB
    invert_colors: False
    cs_pin: 39
    de_pin: 18
    hsync_pin: 16
    vsync_pin: 17
    pclk_pin: 21
    pclk_frequency: 12MHz
    pclk_inverted: False
    hsync_pulse_width: 8
    hsync_front_porch: 10
    hsync_back_porch: 20
    vsync_pulse_width: 8
    vsync_front_porch: 10
    vsync_back_porch: 10
    update_interval: never
    auto_clear_enabled: False
    init_sequence:
      - 1
      - [0xFF, 0x77, 0x01, 0x00, 0x00, 0x10] # CMD2_BKSEL_BK0
      - [0xCD, 0x00] # disable MDT flag
    data_pins:
      red: [11, 12, 13, 14, 0]
      green: [8, 20, 3, 46, 9, 10]
      blue: [4, 5, 6, 7, 15]

touchscreen:
  - platform: gt911
    id: tft_touch
    display: tft_display
#    transform:     #uncomment for placement with down-facing USB socket
#      swap_xy: true
#      mirror_x: true

# LVGL Oberfläche
lvgl:
  displays:
    - tft_display
  touchscreens:
    - tft_touch
  # Definition der UI
  pages:
    - id: main_page
      widgets:
        # Container für die Temperaturen (2x2 Grid)
        - obj:
            height: 120
            width: 300
            align: center
            y: -80
            layout:
              type: grid
              grid_columns: [150, 150]
              grid_rows: [60, 60]
              grid_column_align: space_around
              grid_row_align: space_around
            widgets:
              - label:
                  id: label_wohnzimmer
                  text: "Wohnz: --°C"
                  text_font: font_bold
                  grid_cell_column_pos: 0
                  grid_cell_row_pos: 0
              - label:
                  id: label_buero
                  text: "Büro: --°C"
                  text_font: font_bold
                  grid_cell_column_pos: 1
                  grid_cell_row_pos: 0
              - label:
                  id: label_bad
                  text: "Bad: --°C"
                  text_font: font_normal
                  grid_cell_column_pos: 0
                  grid_cell_row_pos: 1
              - label:
                  id: label_garten
                  text: "Garten: --°C"
                  text_font: font_normal
                  grid_cell_column_pos: 1
                  grid_cell_row_pos: 1
            
        # Der Button
        - button:
            height: 50
            width: 200
            align: center
            y: 50
            widgets:
              - label:
                  text: "Drück mich!"
                  align: center
            
            # Aktion beim Drücken
            on_click:
              - logger.log: "Button wurde gedrückt"

sensor:
  - platform: homeassistant
    id: temp_wohnzimmer
    entity_id: sensor.temperatur_wohnzimmer_temperatur
    on_value:
      - lvgl.label.update:
          id: label_wohnzimmer
          text:
            format: "Wohnz: %.1f°C"
            args: [ 'x' ]
  - platform: homeassistant
    id: temp_buero
    entity_id: sensor.temperatur_buro_temperatur
    on_value:
      - lvgl.label.update:
          id: label_buero
          text:
            format: "Büro: %.1f°C"
            args: [ 'x' ]
  - platform: homeassistant
    id: temp_bad
    entity_id: sensor.thermometer_badezimmer_temperatur
    on_value:
      - lvgl.label.update:
          id: label_bad
          text:
            format: "Bad: %.1f°C"
            args: [ 'x' ]
  - platform: homeassistant
    id: temp_garten
    entity_id: sensor.thermometer_garten_temperature
    on_value:
      - lvgl.label.update:
          id: label_garten
          text:
            format: "Garten: %.1f°C"
            args: [ 'x' ]
