esphome:
  name: esp32-4848s040
  friendly_name: ESP32 Display 4.0

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  flash_size: 8MB
  framework:
    type: esp-idf
    version: 5.2.2
    platform_version: 6.7.0
    sdkconfig_options:
      CONFIG_ESPTOOLPY_FLASHSIZE_8MB: y
      CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: y
      CONFIG_ESP32S3_DATA_CACHE_64KB: y
      CONFIG_SPIRAM_FETCH_INSTRUCTIONS: y
      CONFIG_SPIRAM_RODATA: y



# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "qPC7EIAr2+6hP7NN5HkG5JSh/p5e9oCa8MR/TyhMfz0="

ota:
  - platform: esphome
    password: "1f23fda514f4a4b958e65a6d6f9d0a60"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "4848-Test Fallback Hotspot"
    password: "luvQVO1D0W4T"

captive_portal:

touchscreen:
  platform: ft5x06
  id: my_touchscreen
  transform:
    mirror_x: true
    mirror_y: true

display:
  - platform: st7701s
    id: my_display
    auto_clear_enabled: false
    data_rate: 4MHz
    update_interval: never
    spi_mode: MODE3
    color_order: RGB
    dimensions:
      width: 480
      height: 480
    invert_colors: true
    transform:
      mirror_x: true
      mirror_y: true
    cs_pin:
      pca9554: pca9554a_device
      number: 4
    reset_pin:
      pca9554: pca9554a_device
      number: 5
    de_pin: GPIO18
    hsync_pin: GPIO16
    vsync_pin: GPIO17
    pclk_pin: GPIO21
    init_sequence:
      - 1 # select canned init sequence number 1
      - delay 5ms
      - [ 0xE0, 0x1F ]  # Set sunlight readable enhancement
    data_pins:
      red:
        - GPIO4         #r1
        - GPIO3         #r2
        - GPIO2         #r3
        - GPIO1         #r4
        - GPIO0         #r5
      green:
        - GPIO10        #g0
        - GPIO9         #g1
        - GPIO8         #g2
        - GPIO7         #g3
        - GPIO6         #g4
        - GPIO5         #g5
      blue:
        - GPIO15        #b1
        - GPIO14        #b2
        - GPIO13        #b3
        - GPIO12        #b4
        - GPIO11        #b5

i2c:
  - id: bus_a
    sda: GPIO39
    scl: GPIO40
    scan: false

spi:
  - id: lcd_spi
    clk_pin: GPIO41
    mosi_pin: GPIO48

pca9554:
  - id: pca9554a_device
    address: 0x20
    pin_count: 16


# LVGL Oberfläche
lvgl:
  displays:
    - my_display
  touchscreens:
    - my_touchscreen
  # Definition der UI
  pages:
    - id: main_page
      widgets:
        # Das Label, das den Text anzeigt
        - label:
            id: status_label
            text: "Warte auf Klick..."
            align: center
            y: -50
            
        # Der Button
        - button:
            height: 50
            width: 200
            align: center
            y: 20
            widgets:
              - label:
                  text: "Drück mich!"
                  align: center
            
            # Aktion beim Drücken
            on_click:
              - lvgl.label.update:
                  id: status_label
                  text: "Button gedrückt"